# ============================================================
# MLOps4OFP — Setup local mode
# ============================================================

# ------------------------------------------------------------
# GIT 
# ------------------------------------------------------------
git:
  mode: none

# ------------------------------------------------------------
# DVC — Backend for datasets and artifacts
# ============================================================
dvc:
  backend: local
  path: ./.dvc_storage

# ------------------------------------------------------------
# MLFLOW — Experiments tracking
# ============================================================
mlflow:
  enabled: true
  backend: local
  tracking_uri: file:./mlruns
